# Generated by Django 4.2.9 on 2024-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
